version: '3'
services:
    web:
        image: crypto_web:dev
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
    mocks:
        image: crypto_web:dev
        command: npm run mocks
        ports:
            - 4000:4000
