version: '3'
services:
    web: 
        image: crypto_web:prod
        build:
            context: .
            dockerfile: Dockerfile.prod
        ports: 
            - 80:80
    mocks:
        image: crypto_web:dev
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run mocks
        ports:
            - 4000:4000
